name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        # Fazer upload dos arquivos para PythonAnywhere usando rsync
        rsync -avz --delete-after --exclude '.git*' ./UNIVESP_PI3_RAG_MEDICINE/ $USERNAME@ssh.pythonanywhere.com:~/UNIVESP_PI3_RAG_MEDICINE/

        # Reiniciar a aplicação no PythonAnywhere
        ssh $USERNAME@ssh.pythonanywhere.com << EOF
          source virtualenvwrapper.sh
          workon your_virtualenv
          cd UNIVESP_PI3_RAG_MEDICINE
          pip install -r requirements.txt
          touch reload
        EOF
