name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        # Fazer upload dos arquivos para PythonAnywhere usando rsync
        rsync -avz --delete-after --exclude '.git*' ./UNIVESP_PI3_RAG_MEDICINE/ ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com:~/UNIVESP_PI3_RAG_MEDICINE/

        # Reiniciar a aplicação no PythonAnywhere
        ssh ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << EOF
          cd UNIVESP_PI3_RAG_MEDICINE
          pip install -r requirements.txt
          touch reload
        EOF
