name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Deploy to PythonAnywhere
      uses: appleboy/ssh-action@master
      with:
        host: ssh.pythonanywhere.com
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

          # Fazer upload dos arquivos para PythonAnywhere usando rsync
          rsync -avz --delete-after --exclude '.git*' ./UNIVESP_PI3_RAG_MEDICINE/ ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com:~/UNIVESP_PI3_RAG_MEDICINE/

          # Reiniciar a aplicação no PythonAnywhere
          ssh -i ~/.ssh/id_rsa ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << EOF
            cd UNIVESP_PI3_RAG_MEDICINE
            pip install -r requirements.txt
            touch reload
          EOF
