name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PASSWORD: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
      run: |
        # Fazer upload dos arquivos para PythonAnywhere usando rsync com sshpass
        sshpass -p "${{ secrets.PYTHONANYWHERE_PASSWORD }}" rsync -avz --delete-after --exclude '.git*' ./ ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com:~/UNIVESP_PI3_RAG_MEDICINE/

        # Reiniciar a aplicação no PythonAnywhere
        sshpass -p "${{ secrets.PYTHONANYWHERE_PASSWORD }}" ssh ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << EOF
          cd UNIVESP_PI3_RAG_MEDICINE
          pip install -r requirements.txt
          touch reload
        EOF
